services:
  - type: web
    name: marryme-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py update_all_data
      python scripts/generate_dummy_users.py
      python scripts/generate_dummy_wishlist.py
      python manage.py import_metal_prices
    startCommand: gunicorn weddingProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weddingProject.settings
      - key: SECRET_KEY
        value: your-actual-secret-key
      - key: ALLOWED_HOSTS
        value: .onrender.com