services:
  - type: web
    name: marryme-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn weddingProject.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weddingProject.settings
      - key: SECRET_KEY
        value: your-actual-secret-key
      - key: ALLOWED_HOSTS
        value: .onrender.com