# Generated by Django 4.2.21 on 2025-05-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.PositiveIntegerField(blank=True, null=True)),
                ('gift', models.PositiveIntegerField(blank=True, null=True)),
                ('studio_dress_makeup', models.PositiveIntegerField(blank=True, null=True)),
                ('hall', models.PositiveIntegerField(blank=True, null=True)),
                ('mc', models.PositiveIntegerField(blank=True, null=True)),
                ('officiant', models.PositiveIntegerField(blank=True, null=True)),
                ('congratulator', models.PositiveIntegerField(blank=True, null=True)),
                ('bag_helper', models.PositiveIntegerField(blank=True, null=True)),
                ('snap_dvd', models.PositiveIntegerField(blank=True, null=True)),
                ('flower_shower', models.PositiveIntegerField(blank=True, null=True)),
                ('floral_decor', models.PositiveIntegerField(blank=True, null=True)),
                ('wedding_cake', models.PositiveIntegerField(blank=True, null=True)),
                ('live_music', models.PositiveIntegerField(blank=True, null=True)),
                ('pyebaek', models.PositiveIntegerField(blank=True, null=True)),
                ('pre_wedding_video', models.PositiveIntegerField(blank=True, null=True)),
                ('bouquet', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_table', models.PositiveIntegerField(blank=True, null=True)),
                ('wedding_car', models.PositiveIntegerField(blank=True, null=True)),
                ('honeymoon', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
